// Auto-generated from the official Visit Brussels agenda feed on 2026-05-05.
// Do not edit manually. Re-run the Brussels importer script instead.

export const IMPORTED_BRUSSELS_EVENT_RECORDS = [
  {
    "id": "visit-brussels-5700017566",
    "title": "Happy Hour",
    "shortTitle": "Official Brussels various pick",
    "date": "19 Dec",
    "fullDate": "Friday 19 December 2025 - Thursday 31 December 2026",
    "time": "17:00 - 19:00",
    "place": "Brussels",
    "address": "Share & Fun, Rue Baron Horta, 6, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Various",
    "experience": "Official Brussels various",
    "heroImage": "https://agendabrussels2.imgix.net/1ace7481c07ded3d64437972e6e211dbb6277bf8.jpg",
    "hostName": "Share & Fun",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700017566",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for Happy Hour. Various at Share & Fun in Brussels with 17:00 - 19:00.",
    "tags": [
      "Various",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700011426",
    "title": "Combiticket Atomium + Belgian Beer World Experience",
    "shortTitle": "Official Brussels exhibitions pick",
    "date": "01 Jan",
    "fullDate": "Thursday 01 January 2026 - Wednesday 30 September 2026",
    "time": "10:00 - 18:00",
    "place": "Laeken",
    "address": "Atomium, Atomiumsquare, 1, Laeken",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "37 EUR",
    "priceLabel": "From 37 EUR",
    "vibe": "Exhibitions, Multidisciplinary, Museums and art centers",
    "experience": "Official Brussels exhibitions",
    "heroImage": "https://agendabrussels2.imgix.net/05cd2b88a6acd9009fa02814fe835b88a232f40a.jpg",
    "hostName": "Atomium & Belgian Beer World",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700011426",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Combiticket Atomium + Belgian Beer World Experience. Exhibitions at Atomium in Laeken with Multidisciplinary, Museums and art centers at 10:00 - 18:00.",
    "tags": [
      "Exhibitions",
      "Multidisciplinary",
      "Museums and art centers",
      "Laeken"
    ]
  },
  {
    "id": "visit-brussels-5700020177",
    "title": "Combiticket Best of Belgium",
    "shortTitle": "Official Brussels exhibitions pick",
    "date": "09 Mar",
    "fullDate": "Monday 09 March 2026 - Tuesday 30 June 2026",
    "time": "10:30 - 19:30",
    "place": "Brussels",
    "address": "Belgium Beer World, Choco-Story, Comics Art Museum & Frietmuseum, Belgium Beer World, Choco-Story, Comics Art Museum & Frietmuseum, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "25.5 EUR",
    "priceLabel": "From 25.5 EUR",
    "vibe": "Exhibitions",
    "experience": "Official Brussels exhibitions",
    "heroImage": "https://agendabrussels2.imgix.net/38c5f86fec996e32c0de97edc33fc5e2ff21b875.jpg",
    "hostName": "Belgium Beer World, Choco-Story, Comics Art Museum & Frietmuseum",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020177",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Combiticket Best of Belgium. Exhibitions at Belgium Beer World, Choco-Story, Comics Art Museum & Frietmuseum in Brussels with 10:30 - 19:30.",
    "tags": [
      "Exhibitions",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700019924",
    "title": "Nomad Bar - Every Wednesday",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "25 Feb",
    "fullDate": "Wednesday 25 February 2026 - Wednesday 06 May 2026",
    "time": "22:00 - 23:59",
    "place": "Brussels",
    "address": "Jungle Bar, Jungle Bar, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "5 EUR",
    "priceLabel": "From 5 EUR",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/9731972fc9e4d84f70a147636dfa4b556df68469.jpg",
    "hostName": "The Balcony",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700019924",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Nomad Bar - Every Wednesday. Clubbing at Jungle Bar in Brussels with Afterwork at 22:00 - 23:59.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-518028",
    "title": "Boeremet",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "26 Feb",
    "fullDate": "Thursday 26 February 2026 - Thursday 31 December 2026",
    "time": "18:00 - 23:00",
    "place": "Anderlecht",
    "address": "Anderlecht Abattoir, Rue Ropsy-Chaudron, 24 / 48, Anderlecht",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/f96908d0af3eb986d10af705a1a39507e0b2348f.jpg",
    "hostName": "Anderlecht Abattoir",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-518028",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Boeremet. Clubbing at Anderlecht Abattoir in Anderlecht with Afterwork at 18:00 - 23:00.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Anderlecht",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700020273",
    "title": "BBQ Night at Tipsy Tribe Brewery & Distillery",
    "shortTitle": "Official Brussels various pick",
    "date": "14 Mar",
    "fullDate": "Saturday 14 March 2026 - Friday 25 September 2026",
    "time": "18:00 - 20:00",
    "place": "Koekelberg",
    "address": "Tipsy Tribe Brewery & Distillery, Chaussée de Jette, 374, Koekelberg",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "9 EUR",
    "priceLabel": "From 9 EUR",
    "vibe": "Various",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Tipsy Tribe Brewery & Distillery",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020273",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for BBQ Night at Tipsy Tribe Brewery & Distillery. Various at Tipsy Tribe Brewery & Distillery in Koekelberg with 18:00 - 20:00.",
    "tags": [
      "Various",
      "Koekelberg",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022287",
    "title": "Kunstenfestivaldesarts 2026 : Opening Night",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "08 May",
    "fullDate": "Friday 08 May 2026 - Saturday 09 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "Théâtre Les Tanneurs, Rue des Tanneurs, 75, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/b3c15b0e12fbee115207c7a97e16ba81b77508f3.png",
    "hostName": "Kunstenfestivaldesarts",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022287",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for Kunstenfestivaldesarts 2026 : Opening Night. Clubbing at Théâtre Les Tanneurs in Brussels with 23:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700018505",
    "title": "Bourdon cocktail hour",
    "shortTitle": "Official Brussels markets and bric-a-brac stores pick",
    "date": "24 Apr",
    "fullDate": "Friday 24 April 2026 - Wednesday 30 September 2026",
    "time": "12:00 - 20:30",
    "place": "Uccle",
    "address": "Plaine du Bourdon, Rue Château d’Or, Uccle",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Markets and bric-a-brac stores",
    "experience": "Official Brussels markets and bric-a-brac stores",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Commune d'Uccle",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700018505",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Bourdon cocktail hour. Markets and bric-a-brac stores at Plaine du Bourdon in Uccle with 12:00 - 20:30.",
    "tags": [
      "Markets and bric-a-brac stores",
      "Uccle",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022350",
    "title": "GASOLINA • Latino Boiler Club• Reggaeton Party",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "09 May",
    "fullDate": "Saturday 09 May 2026 - Sunday 10 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "Gasolina Brussels, Rue Duquesnoy, 18, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "17 EUR",
    "priceLabel": "From 17 EUR",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/5858651ae111431900160bb35dea68f7a17d1947.jpeg",
    "hostName": "Gasolina.brussels",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022350",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for GASOLINA • Latino Boiler Club• Reggaeton Party. Clubbing at Gasolina Brussels in Brussels with 23:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022356",
    "title": "COPAIN COCHON : SPRING BANQUET",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "09 May",
    "fullDate": "Saturday 09 May 2026",
    "time": "17:00 - 23:30",
    "place": "Ixelles",
    "address": "UR Square, Avenue de la Couronne, 227, Ixelles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "49 EUR",
    "priceLabel": "From 49 EUR",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/1ca8bbbd897eaa388ef8bfd654cc14adfc43992b.png",
    "hostName": "Blue European Events",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022356",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for COPAIN COCHON : SPRING BANQUET. Clubbing at UR Square in Ixelles with Afterwork at 17:00 - 23:30.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Ixelles",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022352",
    "title": "Last Minute Party",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "09 May",
    "fullDate": "Saturday 09 May 2026",
    "time": "22:00",
    "place": "Saint-Gilles",
    "address": "La Tricoterie, rue Théodore Verhaegen, 158, Saint-Gilles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "15 EUR",
    "priceLabel": "From 15 EUR",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "NCP",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022352",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Last Minute Party. Clubbing at La Tricoterie in Saint-Gilles with 22:00.",
    "tags": [
      "Clubbing",
      "Saint-Gilles",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022359",
    "title": "Mont des Arts PARTY • BACK 2 MUSIC 2000-2010 • International Party",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "09 May",
    "fullDate": "Saturday 09 May 2026 - Sunday 10 May 2026",
    "time": "23:30",
    "place": "Brussels",
    "address": "Plein Publiek Bxm, Mont des Arts, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "5 EUR",
    "priceLabel": "From 5 EUR",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/4005f4b274aa526382f3acd1cbde8294946b23a4.jpg",
    "hostName": "Blue European Events",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022359",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Mont des Arts PARTY • BACK 2 MUSIC 2000-2010 • International Party. Clubbing at Plein Publiek Bxm in Brussels with 23:30.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021242",
    "title": "BEASTS + Let it Kill You",
    "shortTitle": "Official Brussels concert pick",
    "date": "09 May",
    "fullDate": "Saturday 09 May 2026",
    "time": "19:00 - 23:59",
    "place": "Laeken",
    "address": "La Source Beer Co, Rue Dieudonné Lefèvre, 4, Laeken",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Concert, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "La Source Beer Co",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021242",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for BEASTS + Let it Kill You. Concert at La Source Beer Co in Laeken with Pop, rock, jazz… at 19:00 - 23:59.",
    "tags": [
      "Concert",
      "Pop, rock, jazz…",
      "Laeken",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022483",
    "title": "CLUB-MATE OPEN AIR @ Stade Joseph Marien",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "10 May",
    "fullDate": "Sunday 10 May 2026",
    "time": "16:00 - 18:30",
    "place": "Watermael-Boitsfort",
    "address": "LOVIBOND DRINKS | CLUB-MATE, Chaussée de la Hulpe, 185, Watermael-Boitsfort",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "LOVIBOND DRINKS | CLUB-MATE",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022483",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for CLUB-MATE OPEN AIR @ Stade Joseph Marien. Clubbing at LOVIBOND DRINKS | CLUB-MATE in Watermael-Boitsfort with 16:00 - 18:30.",
    "tags": [
      "Clubbing",
      "Watermael-Boitsfort",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-577026",
    "title": "Lorie - Party 2026",
    "shortTitle": "Official Brussels concert pick",
    "date": "10 May",
    "fullDate": "Sunday 10 May 2026",
    "time": "20:00",
    "place": "Forest",
    "address": "Forest National, Avenue Victor Rousseau, Forest",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1772688607088-5f40ead875dc1f2e3c4349a16a90f2dfedca6486.jpg",
    "hostName": "Live Nation",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-577026",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Lorie - Party 2026. Concert at Forest National in Forest with Electro, DJ, Pop, rock, jazz… at 20:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Forest"
    ]
  },
  {
    "id": "visit-brussels-5700021917",
    "title": "Fuse presents: BYORN (all night long)",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "13 May",
    "fullDate": "Wednesday 13 May 2026",
    "time": "23:00 - 23:00",
    "place": "Brussels",
    "address": "Fuse, Rue Blaes, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Fuse",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021917",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Fuse presents: BYORN (all night long). Clubbing at Fuse in Brussels with 23:00 - 23:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-585067",
    "title": "Lucrecia Dalt",
    "shortTitle": "Official Brussels concert pick",
    "date": "14 May",
    "fullDate": "Thursday 14 May 2026",
    "time": "20:30 - 22:00",
    "place": "Brussels",
    "address": "Centre for Fine Arts - Bozar, Rue Ravenstein, 23, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "24 EUR",
    "priceLabel": "From 24 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1764912694344-7c490dc6faf93e0c5ab4afa9a856a455d8b30ec1.jpg",
    "hostName": "Centre for Fine Arts - Bozar",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-585067",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Lucrecia Dalt. Concert at Centre for Fine Arts - Bozar in Brussels with Electro, DJ, Pop, rock, jazz… at 20:30 - 22:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022274",
    "title": "MaccheQuiz - Il Pub Quiz in Italiano di Bruxelles - Feminism 101 edition",
    "shortTitle": "Official Brussels various pick",
    "date": "15 May",
    "fullDate": "Friday 15 May 2026",
    "time": "20:15 - 22:30",
    "place": "Brussels",
    "address": "Maccheroni Comedy IASBL, Rue Franklin, 13, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "24 EUR",
    "priceLabel": "From 24 EUR",
    "vibe": "Various, Games and quiz",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Maccheroni Comedy IASBL",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022274",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for MaccheQuiz - Il Pub Quiz in Italiano di Bruxelles - Feminism 101 edition. Various at Maccheroni Comedy IASBL in Brussels with Games and quiz at 20:15 - 22:30.",
    "tags": [
      "Various",
      "Games and quiz",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021179",
    "title": "Beer Yoga at Tipsy Tribe Brewery & Distillery",
    "shortTitle": "Official Brussels various pick",
    "date": "11 Apr",
    "fullDate": "Saturday 11 April 2026 - Saturday 30 May 2026",
    "time": "11:00 - 12:00",
    "place": "Koekelberg",
    "address": "Tipsy Tribe Brewery & Distillery, Chaussée de Jette, 374, Koekelberg",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "15 EUR",
    "priceLabel": "From 15 EUR",
    "vibe": "Various",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Tipsy Tribe Brewery & Distillery",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021179",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for Beer Yoga at Tipsy Tribe Brewery & Distillery. Various at Tipsy Tribe Brewery & Distillery in Koekelberg with 11:00 - 12:00.",
    "tags": [
      "Various",
      "Koekelberg",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022295",
    "title": "Maman Sort ce Soir",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "16 May",
    "fullDate": "Saturday 16 May 2026",
    "time": "19:00",
    "place": "Brussels",
    "address": "Madame Moustache, Quai au Bois à Brûler, 5-7, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/dbab804ff874ceb05125e7bb894a1bf585da8a28.jpg",
    "hostName": "Madame Moustache",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022295",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Maman Sort ce Soir. Clubbing at Madame Moustache in Brussels with Afterwork at 19:00.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700020976",
    "title": "The Devil made me do it",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "16 May",
    "fullDate": "Saturday 16 May 2026 - Sunday 17 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "The Confessions, Petite Rue au Beurre, 10, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "12 EUR",
    "priceLabel": "From 12 EUR",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "The arena",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020976",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for The Devil made me do it. Clubbing at The Confessions in Brussels with Afterwork at 23:00.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021243",
    "title": "Tattoo Fest : Lou K + Spout Big Space",
    "shortTitle": "Official Brussels concert pick",
    "date": "16 May",
    "fullDate": "Saturday 16 May 2026",
    "time": "11:00 - 23:59",
    "place": "Laeken",
    "address": "La Source Beer Co, Rue Dieudonné Lefèvre, 4, Laeken",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Concert, Pop, Rock, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "La Source Beer Co",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021243",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for Tattoo Fest : Lou K + Spout Big Space. Concert at La Source Beer Co in Laeken with Pop, Rock, Pop, rock, jazz… at 11:00 - 23:59.",
    "tags": [
      "Concert",
      "Pop, Rock",
      "Pop, rock, jazz…",
      "Laeken"
    ]
  },
  {
    "id": "visit-brussels-5700021244",
    "title": "La Sécurité + Yoga Teacher",
    "shortTitle": "Official Brussels concert pick",
    "date": "20 May",
    "fullDate": "Wednesday 20 May 2026",
    "time": "19:00 - 23:59",
    "place": "Laeken",
    "address": "La Source Beer Co, Rue Dieudonné Lefèvre, 4, Laeken",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "11 EUR",
    "priceLabel": "From 11 EUR",
    "vibe": "Concert, Pop, Rock, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "La Source Beer Co",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021244",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for La Sécurité + Yoga Teacher. Concert at La Source Beer Co in Laeken with Pop, Rock, Pop, rock, jazz… at 19:00 - 23:59.",
    "tags": [
      "Concert",
      "Pop, Rock",
      "Pop, rock, jazz…",
      "Laeken"
    ]
  },
  {
    "id": "visit-brussels-586420",
    "title": "Apero Jazz : Adinda Hertmans & Joachim Caffonnette",
    "shortTitle": "Official Brussels concert pick",
    "date": "21 May",
    "fullDate": "Thursday 21 May 2026",
    "time": "18:00",
    "place": "Brussels",
    "address": "Toots Jazz Club, Rue des Chapeliers, 6, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Jazz & Blues, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1776832233638-fb7d75206a0cbb9bb34fedd86b39ec5b39420e75.jpg",
    "hostName": "Toots Jazz Club",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-586420",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Apero Jazz : Adinda Hertmans & Joachim Caffonnette. Concert at Toots Jazz Club in Brussels with Jazz & Blues, Pop, rock, jazz… at 18:00.",
    "tags": [
      "Concert",
      "Jazz & Blues",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-591216",
    "title": "LOTTO BRUSSELS JAZZ WKND : OMER LATE JAM AND AFTER PARTY",
    "shortTitle": "Official Brussels concert pick",
    "date": "22 May",
    "fullDate": "Friday 22 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "Toots Jazz Club, Rue des Chapeliers, 6, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Jazz & Blues, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1776832369068-a2d7fe08fad3f83de5f2318f9cd08adb8d1152a5.jpg",
    "hostName": "Toots Jazz Club",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-591216",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for LOTTO BRUSSELS JAZZ WKND : OMER LATE JAM AND AFTER PARTY. Concert at Toots Jazz Club in Brussels with Jazz & Blues, Pop, rock, jazz… at 23:00.",
    "tags": [
      "Concert",
      "Jazz & Blues",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700020054",
    "title": "The Day Club x Café Luxembourg",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "22 May",
    "fullDate": "Friday 22 May 2026",
    "time": "18:00 - 22:00",
    "place": "Ixelles",
    "address": "Place du Luxembourg, Place du Luxembourg, Ixelles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "10 EUR",
    "priceLabel": "From 10 EUR",
    "vibe": "Clubbing, Afterwork",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/1c2a21fb3d5014a82e4559ec5b08fe441b50792d.png",
    "hostName": "The Day Club",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020054",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for The Day Club x Café Luxembourg. Clubbing at Place du Luxembourg in Ixelles with Afterwork at 18:00 - 22:00.",
    "tags": [
      "Clubbing",
      "Afterwork",
      "Ixelles",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-581078",
    "title": "Bozar Bassment #8: Jokkoo Collective - offcircuit",
    "shortTitle": "Official Brussels concert pick",
    "date": "22 May",
    "fullDate": "Friday 22 May 2026",
    "time": "20:30 - 22:30",
    "place": "Brussels",
    "address": "Centre for Fine Arts - Bozar, Rue Ravenstein, 23, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "18 EUR",
    "priceLabel": "From 18 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1771738213113-08ed65cb0e2f374a077974e5446c3d44a87ee5c6.jpg",
    "hostName": "Centre for Fine Arts - Bozar",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-581078",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Bozar Bassment #8: Jokkoo Collective - offcircuit. Concert at Centre for Fine Arts - Bozar in Brussels with Electro, DJ, Pop, rock, jazz… at 20:30 - 22:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021577",
    "title": "Mura Masa - Doran Electra - Danny L Harle & Many More",
    "shortTitle": "Official Brussels concert pick",
    "date": "22 May",
    "fullDate": "Friday 22 May 2026",
    "time": "18:00",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "42 EUR",
    "priceLabel": "From 42 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/6acc2b41a4ba08e1c2f7d3455d6566e14b2795d8.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021577",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Mura Masa - Doran Electra - Danny L Harle & Many More. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 18:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-591217",
    "title": "LOTTO BRUSSELS JAZZ WKND : OMER LATE JAM AND AFTER PARTY",
    "shortTitle": "Official Brussels concert pick",
    "date": "23 May",
    "fullDate": "Saturday 23 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "Toots Jazz Club, Rue des Chapeliers, 6, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Jazz & Blues, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1776832369479-19771d18f900ec2f1a2dd7cddc65fea96478c3ea.jpg",
    "hostName": "Toots Jazz Club",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-591217",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for LOTTO BRUSSELS JAZZ WKND : OMER LATE JAM AND AFTER PARTY. Concert at Toots Jazz Club in Brussels with Jazz & Blues, Pop, rock, jazz… at 23:00.",
    "tags": [
      "Concert",
      "Jazz & Blues",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022493",
    "title": "BLUR · Circle Park Open Air · with Paranoid London (live), Yentl, Adi, Nina Welch, Bapow",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "23 May",
    "fullDate": "Saturday 23 May 2026",
    "time": "23:00",
    "place": "Brussels",
    "address": "UMI, Rue du Marché aux Fromages, 10, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "15 EUR",
    "priceLabel": "From 15 EUR",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "UMI",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022493",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for BLUR · Circle Park Open Air · with Paranoid London (live), Yentl, Adi, Nina Welch, Bapow. Clubbing at UMI in Brussels with 23:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700020400",
    "title": "Pub Quiz at Tipsy Tribe Brewery & Distillery",
    "shortTitle": "Official Brussels various pick",
    "date": "26 Mar",
    "fullDate": "Thursday 26 March 2026 - Thursday 19 November 2026",
    "time": "18:30 - 20:30",
    "place": "Koekelberg",
    "address": "Tipsy Tribe Brewery & Distillery, Chaussée de Jette, 374, Koekelberg",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "4.99 EUR",
    "priceLabel": "From 4.99 EUR",
    "vibe": "Various, Games and quiz",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Tipsy Tribe Brewery & Distillery",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020400",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for Pub Quiz at Tipsy Tribe Brewery & Distillery. Various at Tipsy Tribe Brewery & Distillery in Koekelberg with Games and quiz at 18:30 - 20:30.",
    "tags": [
      "Various",
      "Games and quiz",
      "Koekelberg",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700014405",
    "title": "Let’s Dance Bitchiz",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "12 Dec",
    "fullDate": "Friday 12 December 2025 - Friday 29 May 2026",
    "time": "20:00",
    "place": "Saint-Gilles",
    "address": "La Tricoterie - Link factory, Rue Théodore Verhaegen, 158, Saint-Gilles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "20 EUR",
    "priceLabel": "From 20 EUR",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/3038855cc4c537142c668c36c18ea741aff9a3a1.png",
    "hostName": "La Tricoterie - Link factory",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700014405",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Let’s Dance Bitchiz. Clubbing at La Tricoterie - Link factory in Saint-Gilles with 20:00.",
    "tags": [
      "Clubbing",
      "Saint-Gilles",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021951",
    "title": "Fuse presents: Rikhter (all night long)",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "29 May",
    "fullDate": "Friday 29 May 2026",
    "time": "23:00 - 07:00",
    "place": "Brussels",
    "address": "Fuse, Rue Blaes, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Fuse",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021951",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Fuse presents: Rikhter (all night long). Clubbing at Fuse in Brussels with 23:00 - 07:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700021659",
    "title": "Fuse presents: Acid night w/ Dr. Rubinstein & Boston 168 (live)",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "30 May",
    "fullDate": "Saturday 30 May 2026 - Sunday 31 May 2026",
    "time": "23:00 - 07:00",
    "place": "Brussels",
    "address": "Fuse, Rue Blaes, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Fuse",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021659",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Fuse presents: Acid night w/ Dr. Rubinstein & Boston 168 (live). Clubbing at Fuse in Brussels with 23:00 - 07:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022113",
    "title": "Fuse presents: Acid Arab (DJ set) & Lefto Early Bird",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "05 Jun",
    "fullDate": "Friday 05 June 2026",
    "time": "23:00 - 07:00",
    "place": "Brussels",
    "address": "Fuse, Rue Blaes, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Fuse",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022113",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for Fuse presents: Acid Arab (DJ set) & Lefto Early Bird. Clubbing at Fuse in Brussels with 23:00 - 07:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-590717",
    "title": "Clubnight by Liaison x Kunty Kompany: DICTATOR’S FUNERAL",
    "shortTitle": "Official Brussels concert pick",
    "date": "05 Jun",
    "fullDate": "Friday 05 June 2026 - Saturday 06 June 2026",
    "time": "23:00 - 23:59",
    "place": "Brussels",
    "address": "Ancienne Belgique, Boulevard Anspach, 110, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "12 EUR",
    "priceLabel": "From 12 EUR",
    "vibe": "Concert, Dance, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1775363500489-6d2fd8f27f4254413225919c5a6367af102bae68.jpg",
    "hostName": "Ancienne Belgique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-590717",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Clubnight by Liaison x Kunty Kompany: DICTATOR’S FUNERAL. Concert at Ancienne Belgique in Brussels with Dance, Pop, rock, jazz… at 23:00 - 23:59.",
    "tags": [
      "Concert",
      "Dance",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-589598",
    "title": "Massive Attack",
    "shortTitle": "Official Brussels concert pick",
    "date": "08 Jun",
    "fullDate": "Monday 08 June 2026",
    "time": "20:00 - 23:00",
    "place": "Forest",
    "address": "Forest National, Avenue Victor Rousseau, Forest",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1772515941986-0ddf4f93342a1dbc57092a951735581350cf66ec.jpg",
    "hostName": "Greenhouse Talent",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-589598",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Massive Attack. Concert at Forest National in Forest with Electro, DJ, Pop, rock, jazz… at 20:00 - 23:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Forest"
    ]
  },
  {
    "id": "visit-brussels-590441",
    "title": "KYLE DIXON & MICHAEL STEIN PERFORMING THE MUSIC OF 'STRANGER THINGS'",
    "shortTitle": "Official Brussels concert pick",
    "date": "10 Jun",
    "fullDate": "Wednesday 10 June 2026",
    "time": "19:00 - 22:30",
    "place": "Brussels",
    "address": "Ancienne Belgique, Boulevard Anspach, 110, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "35 EUR",
    "priceLabel": "From 35 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1775017959413-ad46d18572b6308779a66b9f8f1e54d73d2dc988.jpg",
    "hostName": "Ancienne Belgique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-590441",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for KYLE DIXON & MICHAEL STEIN PERFORMING THE MUSIC OF 'STRANGER THINGS'. Concert at Ancienne Belgique in Brussels with Electro, DJ, Pop, rock, jazz… at 19:00 - 22:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700018210",
    "title": "Colleen",
    "shortTitle": "Official Brussels concert pick",
    "date": "11 Jun",
    "fullDate": "Thursday 11 June 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "17.5 EUR",
    "priceLabel": "From 17.5 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/42d3ddc9a960f50465fc85b316c053c7c6a9d825.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700018210",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Colleen. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-591338",
    "title": "nykolaes & Daniël Paul",
    "shortTitle": "Official Brussels concert pick",
    "date": "11 Jun",
    "fullDate": "Thursday 11 June 2026",
    "time": "19:00 - 22:30",
    "place": "Brussels",
    "address": "Ancienne Belgique, Boulevard Anspach, 110, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "10 EUR",
    "priceLabel": "From 10 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1777177926696-ad5ac8f9596590877e71ab370661da89a5bb0b6b.jpg",
    "hostName": "Ancienne Belgique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-591338",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for nykolaes & Daniël Paul. Concert at Ancienne Belgique in Brussels with Electro, DJ, Pop, rock, jazz… at 19:00 - 22:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022435",
    "title": "BandzAndTankz#16",
    "shortTitle": "Official Brussels concert pick",
    "date": "12 Jun",
    "fullDate": "Friday 12 June 2026",
    "time": "20:00 - 23:00",
    "place": "Anderlecht",
    "address": "Brasserie Drink Drink !, Rue Paepsem, 123, Anderlecht",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "10 EUR",
    "priceLabel": "From 10 EUR",
    "vibe": "Concert, Pop, Rock, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "BandzandTankz",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022435",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for BandzAndTankz#16. Concert at Brasserie Drink Drink ! in Anderlecht with Pop, Rock, Pop, rock, jazz… at 20:00 - 23:00.",
    "tags": [
      "Concert",
      "Pop, Rock",
      "Pop, rock, jazz…",
      "Anderlecht"
    ]
  },
  {
    "id": "visit-brussels-5700021245",
    "title": "Solstice Stoner Fest 2026",
    "shortTitle": "Official Brussels concert pick",
    "date": "13 Jun",
    "fullDate": "Saturday 13 June 2026",
    "time": "12:00 - 23:59",
    "place": "Laeken",
    "address": "La Source Beer Co, Rue Dieudonné Lefèvre, 4, Laeken",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Concert, Pop, Rock, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "La Source Beer Co",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700021245",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for Solstice Stoner Fest 2026. Concert at La Source Beer Co in Laeken with Pop, Rock, Pop, rock, jazz… at 12:00 - 23:59.",
    "tags": [
      "Concert",
      "Pop, Rock",
      "Pop, rock, jazz…",
      "Laeken"
    ]
  },
  {
    "id": "visit-brussels-5700020721",
    "title": "Buckshot",
    "shortTitle": "Official Brussels concert pick",
    "date": "16 Jun",
    "fullDate": "Tuesday 16 June 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "19.65 EUR",
    "priceLabel": "From 19.65 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1e9271c556fe63d93ab182c8aed220e0929a568d.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020721",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Buckshot. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-5700019932",
    "title": "Kumo 99",
    "shortTitle": "Official Brussels concert pick",
    "date": "17 Jun",
    "fullDate": "Wednesday 17 June 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "13 EUR",
    "priceLabel": "From 13 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/b6e4cf5e83c2597a6073b829f2665e7f4cf5b291.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700019932",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Kumo 99. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-581086",
    "title": "Fennesz & Lillevan",
    "shortTitle": "Official Brussels concert pick",
    "date": "20 Jun",
    "fullDate": "Saturday 20 June 2026",
    "time": "20:30 - 22:00",
    "place": "Brussels",
    "address": "Centre for Fine Arts - Bozar, Rue Ravenstein, 23, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "22 EUR",
    "priceLabel": "From 22 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1763875857498-8281ee1b8b7092c8e342498b040bea317157cefe.jpg",
    "hostName": "Centre for Fine Arts - Bozar",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-581086",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Fennesz & Lillevan. Concert at Centre for Fine Arts - Bozar in Brussels with Electro, DJ, Pop, rock, jazz… at 20:30 - 22:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700005859",
    "title": "Mario Kart Championship at Tipsy Tribe Brewery & Distillery",
    "shortTitle": "Official Brussels various pick",
    "date": "18 Oct",
    "fullDate": "Saturday 18 October 2025 - Saturday 17 October 2026",
    "time": "18:30 - 20:30",
    "place": "Koekelberg",
    "address": "Tipsy Tribe Brewery & Distillery, Chaussée de Jette, 374, Koekelberg",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Free",
    "priceLabel": "Free entry",
    "vibe": "Various, Games and quiz",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Tipsy Tribe Brewery & Distillery",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700005859",
    "badge": "FREE ENTRY",
    "description": "Official Visit Brussels listing for Mario Kart Championship at Tipsy Tribe Brewery & Distillery. Various at Tipsy Tribe Brewery & Distillery in Koekelberg with Games and quiz at 18:30 - 20:30.",
    "tags": [
      "Various",
      "Games and quiz",
      "Koekelberg",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700020645",
    "title": "Singles Apero",
    "shortTitle": "Official Brussels various pick",
    "date": "27 Jun",
    "fullDate": "Saturday 27 June 2026",
    "time": "19:00 - 22:30",
    "place": "Ixelles",
    "address": "Full Circle, Chaussée de Vleurgat, 89, Ixelles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Various",
    "experience": "Official Brussels various",
    "heroImage": "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    "hostName": "Full Circle",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020645",
    "badge": "CITY PICK",
    "description": "Official Visit Brussels listing for Singles Apero. Various at Full Circle in Ixelles with 19:00 - 22:30.",
    "tags": [
      "Various",
      "Ixelles",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700022390",
    "title": "Lauren Auder",
    "shortTitle": "Official Brussels concert pick",
    "date": "17 Sep",
    "fullDate": "Thursday 17 September 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "18.5 EUR",
    "priceLabel": "From 18.5 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/565ca0f99360821b62a062af455e484286493f79.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022390",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Lauren Auder. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-591570",
    "title": "Nils Petter Molvær & Tania Giannouli",
    "shortTitle": "Official Brussels concert pick",
    "date": "25 Sep",
    "fullDate": "Friday 25 September 2026",
    "time": "20:15",
    "place": "Ixelles",
    "address": "Flagey, place Sainte-Croix, Ixelles",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "1.25 EUR",
    "priceLabel": "From 1.25 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1777696375951-e1c19a8e5840c78ddc365e7c6fea0f3096b4b5bf.jpg",
    "hostName": "Flagey",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-591570",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Nils Petter Molvær & Tania Giannouli. Concert at Flagey in Ixelles with Electro, DJ, Pop, rock, jazz… at 20:15.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Ixelles"
    ]
  },
  {
    "id": "visit-brussels-590579",
    "title": "gala dragot",
    "shortTitle": "Official Brussels concert pick",
    "date": "08 Oct",
    "fullDate": "Thursday 08 October 2026",
    "time": "19:00 - 22:30",
    "place": "Brussels",
    "address": "Ancienne Belgique, Boulevard Anspach, 110, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "17 EUR",
    "priceLabel": "From 17 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1774758736550-4b959687582c84748656702d4e7860d70c615334.jpg",
    "hostName": "Ancienne Belgique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-590579",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for gala dragot. Concert at Ancienne Belgique in Brussels with Electro, DJ, Pop, rock, jazz… at 19:00 - 22:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Brussels"
    ]
  },
  {
    "id": "visit-brussels-5700015844",
    "title": "La Demence: 37th Anniversary Opening Party",
    "shortTitle": "Official Brussels clubbing pick",
    "date": "30 Oct",
    "fullDate": "Friday 30 October 2026 - Saturday 31 October 2026",
    "time": "22:00",
    "place": "Brussels",
    "address": "La Demence, Rue Blaes, Brussels",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Clubbing",
    "experience": "Official Brussels clubbing",
    "heroImage": "https://agendabrussels2.imgix.net/28caccc8eb0c9176b8b84f8408c2eff5bb69ab08.jpg",
    "hostName": "La Demence",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700015844",
    "badge": "VISIT BRUSSELS",
    "description": "Official Visit Brussels listing for La Demence: 37th Anniversary Opening Party. Clubbing at La Demence in Brussels with 22:00.",
    "tags": [
      "Clubbing",
      "Brussels",
      "Visit Brussels"
    ]
  },
  {
    "id": "visit-brussels-590518",
    "title": "Jungle",
    "shortTitle": "Official Brussels concert pick",
    "date": "31 Oct",
    "fullDate": "Saturday 31 October 2026",
    "time": "18:30 - 23:00",
    "place": "Forest",
    "address": "Forest National, Avenue Victor Rousseau, Forest",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1774503204994-8d8cd50cfe1cebd87f44e00acaabee094139f0dd.jpg",
    "hostName": "Live Nation",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-590518",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Jungle. Concert at Forest National in Forest with Electro, DJ, Pop, rock, jazz… at 18:30 - 23:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Forest"
    ]
  },
  {
    "id": "visit-brussels-5700022271",
    "title": "underscores - umru",
    "shortTitle": "Official Brussels concert pick",
    "date": "06 Nov",
    "fullDate": "Friday 06 November 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "22 EUR",
    "priceLabel": "From 22 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/b55e6f080a196485201f28257687f8a74b5743e6.jpg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700022271",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for underscores - umru. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-5700020596",
    "title": "Digitalism",
    "shortTitle": "Official Brussels concert pick",
    "date": "07 Nov",
    "fullDate": "Saturday 07 November 2026",
    "time": "19:30",
    "place": "Saint-Josse-Ten-Noode",
    "address": "Botanique, Rue Royale, 236, Saint-Josse-Ten-Noode",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "27.65 EUR",
    "priceLabel": "From 27.65 EUR",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/fb72d4ab4deee0314659231648d34e0fc50fcacc.jpeg",
    "hostName": "Botanique",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-5700020596",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Digitalism. Concert at Botanique in Saint-Josse-Ten-Noode with Electro, DJ, Pop, rock, jazz… at 19:30.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Saint-Josse-Ten-Noode"
    ]
  },
  {
    "id": "visit-brussels-588774",
    "title": "Enter Shikari",
    "shortTitle": "Official Brussels concert pick",
    "date": "10 Nov",
    "fullDate": "Tuesday 10 November 2026",
    "time": "18:30 - 23:00",
    "place": "Forest",
    "address": "Forest National, Avenue Victor Rousseau, Forest",
    "attendees": "Official listing",
    "attendeeCount": 0,
    "price": "Ticketed",
    "priceLabel": "Ticket info on Visit Brussels",
    "vibe": "Concert, Electro, DJ, Pop, rock, jazz…",
    "experience": "Official Brussels concert",
    "heroImage": "https://agendabrussels2.imgix.net/1771997536646-6b07b25ac8624003b3200b81045a5e28051bb98e.jpg",
    "hostName": "Live Nation",
    "hostAvatar": "https://i.pravatar.cc/120?u=visit-brussels-588774",
    "badge": "CONCERT",
    "description": "Official Visit Brussels listing for Enter Shikari. Concert at Forest National in Forest with Electro, DJ, Pop, rock, jazz… at 18:30 - 23:00.",
    "tags": [
      "Concert",
      "Electro, DJ",
      "Pop, rock, jazz…",
      "Forest"
    ]
  }
];
